# Generated by Django 3.1.7 on 2021-04-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_auto_20210408_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_sub',
            name='name',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='studentapp.stud_data'),
        ),
    ]
