# Generated by Django 3.1.7 on 2021-04-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_auto_20210408_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'JOB DETAILS',
                'db_table': 'JOB DETAILS',
            },
        ),
        migrations.AlterField(
            model_name='stud_sub',
            name='subject',
            field=models.CharField(choices=[('PYTHON', 'python'), ('DJANGO', 'django')], max_length=100),
        ),
    ]
